### ISSUE TITLE
仕様ライブラリの選定[3H]

### ISSUE THREAD

**Issue by IwamotoW** [Update-hub/roadmap#2]
アローダイアグラムを表示するためのライブラリ剪定
・d3.js
    - https://d3js.org/
    - https://www.npmjs.com/package/d3-node-editor

**Comment by pinoaltotm** [comment]
これはどうだろう？

jsPlumb - Web上で情報の関連性を表現
http://cou929.nu/data/google_javascript_style_guide/
![image](https://user-images.githubusercontent.com/43559254/54025787-f3c79800-41de-11e9-8082-a531f87e12b5.png)

**Comment by deerboy** [comment]
https://jsplumbtoolkit.com
ライセンス的に断念

**Comment by IwamotoW** [comment]
ライブラリ２つほど発見しました。どちらもMITです！
star的にはviz.jsが良さそうですけど、MarkDownDiagramを色々
カスタムして使うのも面白そうです。

・MarkDownDiagram
Qiita
https://qiita.com/wakufactory/items/8a0cf4ffdd52936f7469
GitHub
https://github.com/wakufactory/MarkDownDiagram/tree/master/js
Demo
http://wakufactory.jp/html5/md/mdg/

・viz.js
GitHub
https://github.com/mdaines/viz.js
Demo
http://memopad.bitter.jp/grViz/2.0/jquery/sample04.html

**Comment by deerboy** [comment]
@IwamotoW @pinalto 
これってどういうステータスでしょ

**Comment by IwamotoW** [comment]
ライブラリは2つ見つけたものの、実際に動作するかどうか、カスタムが簡単に可能かどうか詳細を調べるまでには至らなかったので2つのライブラリを@pinaltoに実際に動かして頂く予定です。

引き続き自分がやる予定でしたがwireがやはり必要ではないかとの意見があり、自分が簡単なwireを作り、ライブラリの選定（詳細調査）を@pinaltoさんにお願いする形になりました。

**Comment by deerboy** [comment]
把握しました！ありがとうございます 👍

**Comment by pinalto** [comment]
MarkDownDiagram のソースを眺めてみました。jQueryベースでかなりシンプルですので、改造するベースとしては使いやすいんじゃないかと思います。

データもテキストなのでそのままDBに放り込めます。

サムネイル画像を生成するには他のライブラリを探す必要あり。

**Comment by pinalto** [comment]
しかしそもそも、こういうグラフで表現するのがベストではないかも？😐
たとえば線が交差するようなロードマップはグラフでないと表現しにくいけど、そういう複雑なものはあえて不可にしてもっとシンプルで綺麗に見せた方が受けるかもしれない。

**Comment by deerboy** [comment]
@pinalto 
調査ありがとうございます。
一旦リッチな表現はペンディングにして、HTML/CSSで装飾する程度にしますかね。

**Comment by deerboy** [comment]
一旦なしでfix
