### ISSUE TITLE
進め方の相談 - 2.5H

### ISSUE THREAD

**Issue by deerboy** [Update-hub/roadmap#35]
今週以降の進め方について相談です。

1. 岩本さんのWireを元にIssue棚卸
2. 各自が自分のIssueをとり、開発

### ルール

- 定例MTGは必要に応じて開催（ブレストフェーズを超えたため）
- 仕様変更や提案があれば適宜Issueを立てて全体のコンセンサスを得る
- Issueで議論やタスクを進める（軽微なやり取りはSlackでOK）

## 報酬

最終的に稼働工数（貢献度）を以下に反映([算出ツール](https://deer-inc.github.io/gim/))

- クレジットの掲載順
- マネタイズ時の配分

## MTGについて

- これまでのMTGについては勉強会がマージされていたりと工数化しづらいのでカウント外とする
- 今後のMTGについては開催する場合30分に絞り、参加者に工数付与
- ブレストフェーズを終えたのとメンバーの稼働が安定しているため、定例MTGは適宜開催に変更

## Issueの工数について

```
タイトル - 4H
```

- Issueの工数は実態に応じて設定する
- issueの工数は作成者が設定する
- issueの工数を変更する際はコメントで理由を説明する
- 将来的な利益配分で参照されるので、誠実な設定する

例: https://github.com/Update-hub/roadmap/issues/36

## Mergeについて

- 全員から承認を経る
- 最後に承認した人がマージする

## 開発ルール

オリジナルコンポーネントには`r`プレフィックスをつける（サードパーティライブラリとの区別をつけるため）

---

以上のように考えています。齟齬や提案があればレスください。全員のAgreeをもってFixとします。

ご確認よろしくお願いします。

**Comment by deerboy** [comment]
- 毎週１つはPRだす　をルールから外しました。Issueによっては週をまたぐボリュームになるためなのと、止むを得ない私用で動けない場合もあるためです。
- issueについては作成者が暫定で工数設定を行うフローに変更しました。

対案あればコメントください。

**Comment by deerboy** [comment]
Issueの工数について相談です。

A: 作業者が実態に合わせて自由に変更できる
B: 工数設定、変更は全体、あるいは代表者の合意を得る

のどちらが良いでしょうか？

利益配分で参照されるので工数は慎重に扱いたい反面、フローが複雑化するので作業者が自分で設定できても良いかなと思います。

**Comment by IwamotoW** [comment]
自分はAでお願いしたいです！！　あまりにも常識からはずれた工数が設定された場合だけ聞けばいいと思います！

**Comment by deerboy** [comment]
@IwamotoW 
ありがとうございます！

**Comment by yuFujii** [comment]
自由に変更というか変更する際にissue内にこういう理由で〇H追加します。的な事を言うようにすればslackで流れるのでその時に違和感があれば聞くみたいな感じで良いのではないかなと思います。

**Comment by pinalto** [comment]
@yuFujii 賛成です！

**Comment by deerboy** [comment]
回答ありがとうございます。
Fix & README に記載しておきます。
過去のIssueは引き続き #37 でお願いします。
