### ISSUE TITLE
過去のタスクに工数設定

### ISSUE THREAD

**Issue by deerboy** [Update-hub/roadmap#37]
- [ ] @deerboy 
- [ ] @IwamotoW 
- [ ] @yuFujii 
- [ ] @pinalto 

---

- 工数設定が終わったら工数未定ラベルをつけてこちらにコメントする
- 工数に齟齬がなければコメントに 👍 をつける
- 最後に 👍 した人が工数未定ラベルを外す

その他

- 担当の工数のフォーマットを `xxx - ?H` に変更する

**Comment by deerboy** [comment]
@pinalto @IwamotoW @yuFujii 

https://github.com/Update-hub/roadmap/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+label%3A%E5%B7%A5%E6%95%B0%E6%9C%AA%E7%A2%BA%E5%AE%9A+assignee%3Adeerboy+

上記に工数まとめました。
齟齬なければこのコメントに 👍 お願いします。
最後に 👍 した人はラベル外しお願いします。

**Comment by pinalto** [comment]
https://github.com/Update-hub/roadmap/issues?utf8=✓&q=is%3Aissue+label%3A工数未確定+assignee%3Apinalto+is%3Aclosed+

ご確認よろしくお願い致します。

**Comment by yuFujii** [comment]
https://github.com/Update-hub/roadmap/issues?utf8=%E2%9C%93&q=is%3Aissue+assignee%3AyuFujii+label%3A%E5%B7%A5%E6%95%B0%E6%9C%AA%E7%A2%BA%E5%AE%9A
確認お願いします。

**Comment by pinalto** [comment]
@deerboy 確認完了しました。
