### ISSUE TITLE
UIフレームワークの導入について相談

### ISSUE THREAD

**Issue by deerboy** [Update-hub/roadmap#47]
https://vuetifyjs.com/ja/

上記フレームワーク導入の是非について相談です。

## Pros

- モーダルやボタンなどポピュラーなUIのデザインコストがかからなくなる
- リリースが早まる
- 管理コストが下がる

## Conf

- コンポーネント設計の勉強ができない

---

賛成: 👍 
反対: 😕

**Comment by pinalto** [comment]
コンポーネントの内部設計の勉強にはならなくても外部設計（こっちの方が大事）の勉強にはなるかもしれません？

**Comment by deerboy** [comment]
多数決で導入としますー
