### ISSUE TITLE
nuxt開発環境構築

### ISSUE THREAD

**Issue by deerboy** [Update-hub/roadmap#5]
- [x] CI導入
- [x] 初期化後のPush

**Comment by pinalto** [comment]
@deerboy  circleCIとの接続はリポジトリのオーナーでなくてもできるのでしょうか？

**Comment by deerboy** [comment]
@pinalto
分からないです。無理そうでしたか？

**Comment by pinalto** [comment]
@deerboy 「Add Projects」に出てこないので、無理なのかなと。

**Comment by deerboy** [comment]
権限変えてみたので再度みてみてください

**Comment by pinalto** [comment]
出てこないです・・・

![image](https://user-images.githubusercontent.com/43559254/54584565-10739380-4a5b-11e9-94f9-4581e2e6b9c7.png)

**Comment by pinalto** [comment]
- CiecleCIとの連携を設定しました。
- masterブランチのprotectionを設定しました。

**Comment by deerboy** [comment]
@pinalto 
ありがとうございます😊！
