### ISSUE TITLE
簡易wire作成[3H]

### ISSUE THREAD

**Issue by IwamotoW** [Update-hub/roadmap#9]

**Comment by deerboy** [comment]
ありがとうございます！以下僕からのFBです。

Wireで重要なのはデザインではなく、

- どの画面にどの情報があるか
- どの操作をすれば何が起きるか

がクリアになっていること。その上で、

- これらボタンを押したらどうなる？

![image](https://user-images.githubusercontent.com/5842851/54860047-cb4faa00-4d57-11e9-81f7-dc8d1cc69b71.png)

- ヘルプ押したらどうなる？
- 編集画面に保存ボタンはなくて良いか？
- 保存ボタンを押したさい、なんらかのインタラクションは不要か？（「保存しました。」というトースターなど）
- エラーの時はどうなる？（文字数制限を超えて保存しようとしたらエラーが出るのか、あるいはそもそも上限以上は入力できないのか）
- すでに投稿したものを編集するにはどういう導線で編集画面に飛ぶか

などが気になりました！

来週末までで結構なので、よろしくお願いします！ :)
